title: Mathias Lauber
logo: /img/imgfinal.png
description: Mathias.Lauber@outlook.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# Sidebar settings
sidebar:
  position: right  # or right
  sticky: true    # Set to true if you want a sticky sidebar
  # Custom CSS settings
custom_css:
  logo:
    max-width: 50px
    height: 50px
