title: Mathias Lauber
logo: /img/img.jpeg
#logo: /assets/img/headshot_circle.png




# Thème à utiliser (minimal) ##slate
theme: jekyll-theme-minimal
showdownloads: true


# Paramètres globaux
subtitle: DataViz / Data nerd
author: Mathias Lauber
email: Mathias.Lauber@outlook.com
