showdownloads: true
logo: img.jpeg



# Nom de votre site
name: Mathias Lauber Portefolio

# Description de votre site
description: Bienvenue sur mon portfolio en ligne !

# Thème à utiliser (minimal) ##slate
theme: jekyll-theme-minimal

# Configuration spécifique au thème minimal
theme_config:
  # Liens sociaux
  github_username: votre-nom-d-utilisateur-github
  twitter_username: votre-nom-twitter
  linkedin_username: votre-nom-linkedin

  # Paramètres pour la barre latérale
  show_sidebar: true
  sidebar_items:
    - title: side bar
      url: /
    - title: Projets
      url: /projects
    - title: Blog
      url: /blog

# Paramètres globaux
title: Mathias Lauber
subtitle: DataViz / Data nerd
author: Mathias Lauber
email: Mathias.Lauber@outlook.com
